name: 'Terraform Infra Pipeline'

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_USE_OIDC: true

jobs:
  infra-deployment:
    name: 'Terraform, Scans & Deploy'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: '.' # Kyunki screenshot ke hisaab se code root folder me hai

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login via OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="resource_group_name=RG-DO-NOT-DELETE" \
          -backend-config="storage_account_name=fleetstorage1" \
          -backend-config="container_name=container1" \
          -backend-config="key=aks-cluster.tfstate"

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: TFLint Code Scan
      run: |
        curl -sL https://github.com/terraform-linters/tflint/releases/latest/download/tflint_linux_amd64.zip -o tflint.zip
        unzip tflint.zip
        sudo mv tflint /usr/local/bin/
        tflint --init
        tflint -f compact

    - name: Checkov Security Scan
      run: |
        pip3 install checkov
        checkov -d . --soft-fail

    - name: Setup Infracost
      uses: infracost/actions/setup@v3
      with:
        api-key: ico-bjjsUNbF5NSCVN5pUaG7WY2QKu1M7z5c

    - name: Run Infracost Breakdown
      run: infracost breakdown --path . --format html --out-file infracost-report.html

    - name: Publish Infracost Report
      uses: actions/upload-artifact@v4
      with:
        name: InfracostReport
        path: infracost-report.html

    - name: Terraform Apply
      # Sirf 'main' branch me push hone par hi apply chalega
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan